#version: "3.9"

services:
  postgres:
    image: postgres:15.1
    container_name: postgres-db1
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data1

volumes:
  pgdata:

